### ISSUE TITLE
SPEC: "wrong" dependencies and pkgname

### ISSUE THREAD

**Issue by pirat89** [leapp-to/snactor#75]
Just giving you note, that you should replace `python-*` dependencies by `python2-*` dependencies for fedora. In the same meaning, the name of the `python-snactor` package should be changed to `python2-snactor`

>According to Fedora Packaging guidelines for Python, packages must use names with either python2- or python3- prefix in requirements where available.
We are aiming to rename python-* dependencies to python2-*, so we can later switch the python-* namespace to Python 3.

>This PR is part of Fedora's Switch to Python 3 effort.

https://fedoraproject.org/wiki/Packaging:Python#Dependencies
https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3

**Comment by pirat89** [comment]
Something like that could be the solution, but probably in that case you will need to fix spec files of other packages that are dependenc on `python-snactor`:

```diff
diff --git a/python-snactor.spec b/python-snactor.spec
index ae9d531..ce1c8f3 100644
--- a/python-snactor.spec
+++ b/python-snactor.spec
@@ -1,6 +1,6 @@
 %global debug_package %{nil}
 
-Name:       python-snactor
+Name:       python2-snactor
 Version:    0.2
 Release:    40.1
 Summary:    Python Actor execution library
@@ -37,7 +37,7 @@ Requires:       python-six
 BuildRequires:       python-six
 %else
 Requires:       python2-six
-BuildRequires:       python-six
+BuildRequires:  python2-six
 %endif
 
 %description

```

**Comment by vinzenz** [comment]
That only works for fedora and not for CentOS7, so this has to be done with a ifdef, anyway snactor is able to run in Python 3 so we will see if we won't switch to it anyway.

Long story short, we dropped the spec file from here to the all integrated leapp.spec in the leapp-to/leapp repo so this became obsolete anyway thanks for reporting
