### ISSUE TITLE
Snactor config file location

### ISSUE THREAD

**Issue by GAZDOWN** [leapp-to/snactor#77]
We should have snactor.cfg file in /etc/snactor/ by default (or similar location) rather than in CWD or $HOME. This way we will be able to execute the snactor by any user without making mess in FS.

**Comment by vinzenz** [comment]
> rather than in CWD or $HOME

There is nothing wrong with having those available and we don't have any default snactor.cfg at this moment.

IIUC you would like to recommend to support a global place in etc that can be used to configure those paths on system level and be overridden by having a config in $CWD or in $HOME. And additionally to that to actually have a default configuration installed to the /etc/ location based on the installed actor repository location, is that about right?

**Comment by pirat89** [comment]
Related PR: https://github.com/leapp-to/leapp-actors/pull/35

Note: the SPEC file (wherever it is now) would be modified as well later by adding a line into the `%files` section, like:
```
%config(noreplace)%{_sysconfdir}/snactor/snactor.cfg
```

Not sure about path - in the PR is used `/etc/leapp` instead of `/etc/snactor`.
